#!/bin/sh
set -e

case "$1" in
    remove|purge|disappear)
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database -q || true
        fi
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
            for dir in /usr/share/icons/hicolor; do
                [ -d "$dir" ] && gtk-update-icon-cache -q "$dir" || true
            done
        fi
    ;;
	esac

#DEBHELPER#

exit 0
